import libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


Import dataset and remove unwanted columns

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/NLP/dataset.csv')
df = df.iloc[0:100,2:4]
df

Statement Positive/Negative
0   සාමාන්‍යයෙන් පෞද්ගලික චරිත ගැන ලියන්න හොද  නෑ....          Positive
1   මම නුවරඑළියේ ඉදන් කොළඹට ඇවිල්ලා ගායකයෙක් වෙන්න...          Positive
2   Ego system Vs. Eco system \n\nසාමාන්‍යයෙන් ලංක...          Positive
3   අද උදේ දැකපු සුන්දර දර්ශණයක්. නුගේගොඩ St.Johns...          Positive
4   Smoking is a bad habit \nMenda , Danee🏏✌.\nCri...          Positive
..                                                ...               ...
95  2022 බුකර් සම්මානය ලත් විශිෂ්ටතම කෘතිය  ශෙහාන්...          Positive
96  ක්‍රිකටර්ස්ලත්  මිනිස්සු...සාමාන්‍යයෙන් පෞද්ගල...          Positive
97  අද gaming/Streaming field එකේ ඉන්න අපේ තරුණ කෙ...          Positive
98  ක්‍රමිකව ප්‍රාථමික අධ්‍යාපනයේ සිට සහා ගුරු පුහ...          Negative
99  සයිබර් අපරාධ දෙකේ කොලේට දාලා කතාකරන පණ්ඩිත දාර...          Negative

[100 rows x 2 columns]

finding the null values

In [ ]:
df.isnull().any()

Statement            True
Positive/Negative    True
dtype: bool

number of null values

In [ ]:
df.isnull().sum()

Statement            1
Positive/Negative    1
dtype: int64

In [ ]:
df.shape

(100, 2)

remove null values

In [ ]:
df.dropna(subset = ["Positive/Negative"], inplace=True)
print(df.isnull().sum())
print(df.shape)

Statement            0
Positive/Negative    0
dtype: int64
(99, 2)


reset index

In [ ]:
df = df.reset_index(drop=True)

replace positive with 1 and replace negative with 0

In [ ]:
df['Positive/Negative'].replace('Positive', 1, True)
df['Positive/Negative'].replace('Negative', 0, True)
df

Statement  Positive/Negative
0   සාමාන්‍යයෙන් පෞද්ගලික චරිත ගැන ලියන්න හොද  නෑ....                  1
1   මම නුවරඑළියේ ඉදන් කොළඹට ඇවිල්ලා ගායකයෙක් වෙන්න...                  1
2   Ego system Vs. Eco system \n\nසාමාන්‍යයෙන් ලංක...                  1
3   අද උදේ දැකපු සුන්දර දර්ශණයක්. නුගේගොඩ St.Johns...                  1
4   Smoking is a bad habit \nMenda , Danee🏏✌.\nCri...                  1
..                                                ...                ...
94  2022 බුකර් සම්මානය ලත් විශිෂ්ටතම කෘතිය  ශෙහාන්...                  1
95  ක්‍රිකටර්ස්ලත්  මිනිස්සු...සාමාන්‍යයෙන් පෞද්ගල...                  1
96  අද gaming/Streaming field එකේ ඉන්න අපේ තරුණ කෙ...                  1
97  ක්‍රමිකව ප්‍රාථමික අධ්‍යාපනයේ සිට සහා ගුරු පුහ...                  0
98  සයිබර් අපරාධ දෙකේ කොලේට දාලා කතාකරන පණ්ඩිත දාර...                  0

[99 rows x 2 columns]

add to data frame statement to x variable

In [ ]:
x = df['Statement']

In [ ]:
x

0     සාමාන්‍යයෙන් පෞද්ගලික චරිත ගැන ලියන්න හොද  නෑ....
1     මම නුවරඑළියේ ඉදන් කොළඹට ඇවිල්ලා ගායකයෙක් වෙන්න...
2     Ego system Vs. Eco system \n\nසාමාන්‍යයෙන් ලංක...
3     අද උදේ දැකපු සුන්දර දර්ශණයක්. නුගේගොඩ St.Johns...
4     Smoking is a bad habit \nMenda , Danee🏏✌.\nCri...
                            ...                        
94    2022 බුකර් සම්මානය ලත් විශිෂ්ටතම කෘතිය  ශෙහාන්...
95    ක්‍රිකටර්ස්ලත්  මිනිස්සු...සාමාන්‍යයෙන් පෞද්ගල...
96    අද gaming/Streaming field එකේ ඉන්න අපේ තරුණ කෙ...
97    ක්‍රමිකව ප්‍රාථමික අධ්‍යාපනයේ සිට සහා ගුරු පුහ...
98    සයිබර් අපරාධ දෙකේ කොලේට දාලා කතාකරන පණ්ඩිත දාර...
Name: Statement, Length: 99, dtype: object

install google translate

In [ ]:
!pip install googletrans==4.0.0-rc1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


import google translate

In [ ]:
import googletrans
from googletrans import Translator

In [ ]:
# Create translation model
translator = Translator()

translated from sinhala to english

In [ ]:
for i in range(len(x)):
  translation = translator.translate(x[i],dest="en")
  x[i] = translation.text
  print('statement', i , ':', x[i])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


statement 0 : We do not usually write about personal characters. There is no matter what it is like.

The Team in Sri Lanka..We want Sri Lanka.
From Sri Lanka, we are hembiriissa ... 😊

Crictorslah people!

Bring lions bring the cup ..
statement 1 : I am from Nuwara Eliya and trying to be a singer. Roshan Fernando brother is a legend of the music music, which has many years of experience in the music industry. For the first time, Flash Back Back to the Practice.

It is fortty fortunate to have a loving-acceptance and meetings.

They are all beautiful people.
Let us share us on the stage ... let's down
statement 2 : EGO System vs. Eco system

Generally, people in Sri Lanka have used to work together with the Ego System. There is one who is the leader. The leader knows everything. The leader commands others. Says things to be. The leader wants to hear, and tell the leader's rejoice. Everyone has their own parts. They have power struggles to protect these parts. People cling to those powe

import and downlode libraries

In [ ]:
import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


remove stop words

In [ ]:
stopWords = set(stopwords.words('english'))
posterStemer = PorterStemmer()
corpus = []
for i in range(len(x)):
  comment = x[i].lower()
  comment = re.sub(r"http\S+|www\S+|https\S+", '',comment)
  comment = re.sub(r'\@\w+|\#',' ',comment)
  comment = re.sub('[^a-z]', ' ', comment)
  comment_token = nltk.word_tokenize(comment)
  comment = [posterStemer.stem(word) for word in comment_token if word not in stopWords]
  comment = ' '.join(comment)
  corpus.append(comment)
  print('caption', i , ':', comment)

caption 0 : usual write person charact matter like team sri lanka want sri lanka sri lanka hembiriissa crictorslah peopl bring lion bring cup
caption 1 : nuwara eliya tri singer roshan fernando brother legend music music mani year experi music industri first time flash back back practic fortti fortun love accept meet beauti peopl let us share us stage let
caption 2 : ego system vs eco system gener peopl sri lanka use work togeth ego system one leader leader know everyth leader command other say thing leader want hear tell leader rejoic everyon part power struggl protect part peopl cling power struggl mankind time liber democrat movement base eco system ego system friend eco system learn one commun knowledg share propos accept respons other honestli express view respons help feed therefor whatev work rich connect liber democrat movement ldm discuss group profession build countri run eco system ego system srilanka life
caption 3 : beauti display seen morn nugegoda st joshn colleg learn b

In [ ]:
corpus

['usual write person charact matter like team sri lanka want sri lanka sri lanka hembiriissa crictorslah peopl bring lion bring cup',
 'nuwara eliya tri singer roshan fernando brother legend music music mani year experi music industri first time flash back back practic fortti fortun love accept meet beauti peopl let us share us stage let',
 'ego system vs eco system gener peopl sri lanka use work togeth ego system one leader leader know everyth leader command other say thing leader want hear tell leader rejoic everyon part power struggl protect part peopl cling power struggl mankind time liber democrat movement base eco system ego system friend eco system learn one commun knowledg share propos accept respons other honestli express view respons help feed therefor whatev work rich connect liber democrat movement ldm discuss group profession build countri run eco system ego system srilanka life',
 'beauti display seen morn nugegoda st joshn colleg learn bhathkand univers india india teach

trnsform sentence to word and add to positive/negative column to y variable

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1400)
X = cv.fit_transform(corpus).toarray()
y = df.iloc[:, -1].values

In [ ]:
y

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0])

In [ ]:
# no of features/columns/words in X
len(X[0])

1400

split data set as train and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 4)

add and train model. use naive bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

compare actual and test values

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]]


find the accuracy in model

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[7 1]
 [4 8]]


0.75

this model has 75% accuracy